# Generated by Django 5.0.2 on 2024-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
